spring:
  datasource:
    url: jdbc:mysql://mysql:3306/poultrydb?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  data:
    mongodb:
      host: mongo
      port: 27017
      database: poultrydb
server:
  port: 8080
